//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDelivery
    {
        public int ID { get; set; }
        public int NotificationID { get; set; }
        public Nullable<int> NotificationMethodID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual NotificationMethod NotificationMethod { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
