//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NotificationsMessages
    {
        public long PrimaryKeyID { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string UserID { get; set; }
        public string SenderUserID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Abstract { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> NotificationsDateCreated { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> MessagesContractID { get; set; }
        public string MessagesRecipientUserID { get; set; }
        public string MessagesSenderUserID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> MessagesRecipientViewed { get; set; }
        public Nullable<bool> MessagesSenderDeleted { get; set; }
        public Nullable<bool> MessagesRecipientDeleted { get; set; }
        public Nullable<System.DateTime> MessagesDateCreated { get; set; }
    }
}
