//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Notifications
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string SenderUserID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> NotificationMessageID { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
        public string Body { get; set; }
        public string SenderFirstName { get; set; }
        public string SenderLastName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string SenderCompanyName { get; set; }
        public string TaskStatusName { get; set; }
        public string TaskTypeName { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> MinutesUntilTaskExpires { get; set; }
    }
}
